In [1]:
# Numpy is a python library used for working with arrays. It has function for working with domain of linear algebra, fourier transform and matrices.
# The array object in numpy is called ndarray. We can create the numpy array object by using the "array()"" object

In [2]:
import numpy as np
print(np.__version__) 

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

In [10]:
# a dimension in array is one level of array depth

In [17]:
# 0-D array
arr = np.array(45)
print("0-D or scalar: ", arr)

#1-D array
arr1 = np.array([1,2,3,4])
print("1-D or Unidimensional: ", arr1)

# 2-D array. often used to represent matrices or second order tensors
arr2 = np.array([[1,2,3],[4,5,6]])
print("2-D:", arr2)

# 3-D array. There are often used to represent a 3rd order tensors
arr3 = np.array([[[1,2,3],[4,5,6]]])
print("3-D:", arr3)

0-D or scalar:  45
1-D or Unidimensional:  [1 2 3 4]
2-D: [[1 2 3]
 [4 5 6]]
3-D: [[[1 2 3]
  [4 5 6]]]


# Check Number of Dimension

In [19]:
# the "ndim" is used to check the number of dimension of an array
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1


# Higher Dimensional Array


In [22]:
# when an array is created, you can specify the number of dimension by using "ndmin"
# The below line of code will give a 5-D array

arr1 = np.array([1,2,3,4,5], ndmin=5)
print(arr1)
print("The number of dimension is:",arr1.ndim)

[[[[[1 2 3 4 5]]]]]
The number of dimension is: 5


# Array Indexing

In [24]:
# array indexing is thesame with most programming languages. It starts with index 0.

arr1 = np.array([1,2,3,4])
print(arr1[1] + arr1[3])

6


In [32]:
# Accessing a 2-d array we use comma separated integers to represent the array and the indexing
# The code below will produce 1st index of the first array object

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,2])

# Acessing 3-d array. The code below will produce 5
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1[0, 1, 1])

# negative indexing is used to access array from the end
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2[1, -3])

3
5
8


# Array Slicing

In [41]:
# This means taking an array from one given index to another index. [start, end, step]. it using excludes the end value

arr = np.array([1,2,3,4,5,6,7,8])
print("Takes from index 1 excluding index 5:",arr[1:5])
print("Takes from index 1 excluding index 5, in steps of 2:",arr[1:5:2])
print("Takes from index 0 excluding index 4:",arr[:4])
print("Takes from index 4 to the end:",arr[4:])

Takes from index 1 excluding index 5: [2 3 4 5]
Takes from index 1 excluding index 5, in steps of 2: [2 4]
Takes from index 0 excluding index 4: [1 2 3 4]
Takes from index 4 to the end: [5 6 7 8]


In [44]:
# Slicing 2-d

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2,2])

[7 8 9]
[3 8]
