In [6]:
# ufuncs stands for universal functions and they are numpy functions that operates on the ndarray object

# Why use ufuncs?
# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
# They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
# ufuncs also take additional arguments, like:
# where boolean array or condition defining where the operations should take place.
# dtype defining the return type of elements.
# out output array where the return value should be copied.










In [10]:
import numpy as np
# Add the elements of 2 arrays

print("Without the numpy ufunc")
x = [1,2,3,4]
y = [5,6,7,8]
z = []

for i,j in zip(x,y):
    z.append(i+j)
print(z)

print("")

print("with the numpy ufunc")
x = [1,2,3,4]
y = [5,6,7,8]
z = np.add(x,y)
print(z)

Without the numpy ufunc
[6, 8, 10, 12]

with the numpy ufunc
[ 6  8 10 12]


# Create your own ufunc

In [2]:
import numpy as np
# To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.
# The frompyfunc() method takes the following arguments:
# function - the name of the function.
# inputs - the number of input arguments (arrays).
# outputs - the number of output arrays.

In [12]:
def myadd(x,y):
    return x + y

myadd = np.frompyfunc(myadd, 2, 1)
    
x = myadd([1,2,3,4], [5,6,7,8])
print(type(np.add))


<class 'numpy.ufunc'>


# SIMPLE ARITHMETIC

In [ ]:
# You can use arithmetic operation directly on numpy arrays. +-/*
# Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.
# All of the discussed arithmetic functions take a where parameter in which we can specify that condition.





In [19]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr1 = np.add(arr1,arr2)
newarr2 = np.subtract(arr1,arr2)
newarr3 = np.divide(arr1,arr2)
newarr4 = np.multiply(arr1,arr2)
newarr5 = np.mod(arr1,arr2)
newarr6 = np.divmod(arr1,arr2)


print(newarr1)
print(newarr2)
print(newarr3)
print(newarr4)
print(newarr5)
print(newarr6)

# others include: absolute, power, remainder

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[200 231 264 299 336 375]
[10 11 12 13 14 15]
(array([0, 0, 0, 0, 0, 0], dtype=int32), array([10, 11, 12, 13, 14, 15], dtype=int32))


# ROUNDING DECIMAL

In [37]:
# There are primarily 5 ways of decimals in numpy
# truncating, rounding, fix, floor, ceil

x = np.trunc([-2.6782, 3.999])
print(x)

x = np.round(3.556,2)
print("Round:", x)

arr = np.fix([-3.1666, 3.6667])
print(arr)
arr = np.floor([-3.1666, 3.6667])
print("Floor:", arr)
arr = np.ceil([-3.1666, 3.6667])
print("Ceil:", arr)

[-2.  3.]
Round: 3.56
[-3.  3.]
Floor: [-4.  3.]
Ceil: [-3.  4.]


# NumPy Logs

In [ ]:
# numpy provides function to work at base 2, e and 10
# All of the log functions will place -inf or inf in the elements if the log can not be computed.

In [8]:
import numpy as np
from math import log

In [10]:
arr = np.arange(1,10)

print(np.log2(arr))
print("Log at base 10",np.log10(arr))
print(f"Natural log:\n {np.log(arr)}")


# Log at Any Base
# NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt
# function math.log() with two input parameters and one output parameter:
print("")
nplog = np.frompyfunc(log,2,1)
print(f"Log at any Base {nplog(100,15)}")





[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
Log at base 10 [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
Natural log:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]

Log at any Base 1.7005483074552052


# NumPy Summations

In [14]:
# What is the difference between summation and addition?
# Addition is done between two arguments whereas summation happens over n elements.

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

arr = np.add(arr1, arr2)
arr3 = np.sum([arr1,arr2])

print(f"Addition: {arr}")
print(f"Summation: {arr3}")



Addition: [2 4 6]
Summation: 12


In [15]:
# Cummulative Sum
# Cummulative sum means partially adding the elements in array.
# E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
# Perfom partial sum with the cumsum() function

arr  = np.array([1,2,3,4,5])
x = np.cumsum(arr)
print(x)

[ 1  3  6 10 15]


# NumPy Products

In [24]:
# To find the product of the elements in an array, use the prod() function.

arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])

x = np.prod(x)
y = np.prod([arr,arr1])

print(x)
print(y)

# PRODUCT OVER AXIS
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(F"Product over axis: {newarr}")

# Cummulative product means taking the product partially.
# E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]
# Perfom partial sum with the cumprod() function.

arr = np.array([5,6,7,8])
arr1 = np.cumprod(arr)
print(f"cumulative product: {arr1}")





2700
3628800
Product over axis: [  24 1680]
cumulative product: [   5   30  210 1680]


# NumPy Differences

In [26]:
# A discrete difference means subtracting two successive elements.

# E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

# To find the discrete difference, use the diff() function.

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)


arr = np.array([10,15,25,5])
newarr = np.diff(arr, n=2)
print(newarr)






[  5  10 -20]
[  5 -30]


# Numpy LCM

In [43]:
# The Lowest Common Multiple is the least number that is common multiple of both of the numbers.

num1 = 4
num2 = 6
result = np.lcm(num1,num2)
print(result)

# Returns: 12 because that is the lowest common multiple of both numbers (4*3=12 and 6*2=12).

# FINDING LCM IN ARRAY:
# to find the lcm in an array, we use the reduce() method 

arr1 = np.array([1,2,3])
result = np.lcm.reduce(arr1)
print(result)

print("")
print(f"Find the LCM of all of an array where the array contains all integers from 1 to 10:")

arr = np.arange(1,11)
arr1 = np.lcm.reduce(arr)
print(arr1)

# Convert Degrees Into Radians
# By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumP.
# Note: radians values are pi/180 * degree_values.
print("")
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(f"Converting radian to degrees:", x)
print("")

# Finding Angles
# Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

# NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

arr = np.array([1,-1, 0.1])
x = np.arcsin(arr)
print("Find the angle for all of the sine values in the array: ",x)













12
6

Find the LCM of all of an array where the array contains all integers from 1 to 10:
2520

Converting radian to degrees: [ 90. 180. 270. 360.]

Find the angle for all of the sine values in the array:  [ 1.57079633 -1.57079633  0.10016742]


# Trigonometric Functions

In [45]:
# Numpy provides funtion in sin() cos() and tan() that takes values in radians and produe the cresspnding sin, cos, and tan values

# converting degree to radian
# radian_value = PI/180 * degree_value

x = np.sin(np.pi/2)
print(x)

# finding values for all values in an array
arr = np.array([np.pi/2, np.pi/3, np.pi/3, np.pi/4, np.pi/5])
result = np.sin(arr)
print(result)

# Hypotenues
# Finding hypotenues using pythagoras theorem in NumPy.

# NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.
base = 3
perp = 4
side= np.hypot(base, perp)
print(side)


1.0
[1.         0.8660254  0.8660254  0.70710678 0.58778525]
5.0


# NumPy GCD Greatest Common Denominator

In [7]:
# The GCD (gREATEST COMMON DENOMINATOR) also known as HCF(Highest common factor) is  the biggest number that is common to both numbers.

import numpy as np

x = 6
y = 9
z = np.gcd(x,y)
print(z)
print("Returns: 3 because that is the highest number both numbers can be divided by (6/3=2 and 9*3=3).")

# FINDING GCD IN ARRAYS
# to find the hcf of all arrays, you can use the reduce method

x = np.array([6,9,18])
y = np.gcd.reduce(x)
print(y)

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)










3
Returns: 3 because that is the highest number both numbers can be divided by (6/3=2 and 9*3=3).
3
4


# HYPERBOLIC FUNCTION

In [16]:
# NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..
import numpy as np

x = np.sinh(np.pi/2)
print(x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print("Finding the cosh of all values of an array",x)

# FINDING ANGLES
# Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

# Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

x =np.arccosh(45)
print("ARCCOSH: ",x)

print("")
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)
print(f"Angle of each value in n array:\n {x}")





2.3012989023072947
Finding the cosh of all values of an array [2.50917848 1.60028686 1.32460909 1.20397209]
ARCCOSH:  4.499686190671499

Angle of each value in n array:
 [0.10033535 0.20273255 0.54930614]


# NumPy Set Operations

In [ ]:
# A set is the collection of unique elements.
# Sets are used for operation involving frequent intersection, union and difference operation
# Set array should only be 1-d array

# To find the union of two arrays, use the union1d()
# To find the vales that are present in the both arrays, use the intersect1d() method
# To only find  the values that are not present in both set we use the setxor1d().


# union1d(), interset1d(), unique(), setdiff1d()


In [23]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
result = np.unique(arr)
print(result)
print("")
print("Finding the union of 2 arrays:")
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
result = np.union1d(arr1,arr2)
print(result)

result1 = np.intersect1d(arr1, arr2, assume_unique=True)
print(result1)

# Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
# It should always be set to True when dealing with sets.




[1 2 3 4 5 6 7]

Finding the union of 2 arrays:
[1 2 3 4 5 6]
[3 4]


In [25]:
# FINDING DIFFERENCE
import numpy as np

# To find only arrays that are in the first set but are not present in the second, we use the setdiff1d() method.
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

result = np.setdiff1d(set1, set2, assume_unique=True)
result1 = np.setxor1d(set1, set2, assume_unique=True)

print(result)
print(result1)


[1 2]
[1 2 5 6]
