In [6]:
# ufuncs stands for universal functions and they are numpy functions that operates on the ndarray object

# Why use ufuncs?
# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
# They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
# ufuncs also take additional arguments, like:
# where boolean array or condition defining where the operations should take place.
# dtype defining the return type of elements.
# out output array where the return value should be copied.










In [10]:
import numpy as np
# Add the elements of 2 arrays

print("Without the numpy ufunc")
x = [1,2,3,4]
y = [5,6,7,8]
z = []

for i,j in zip(x,y):
    z.append(i+j)
print(z)

print("")

print("with the numpy ufunc")
x = [1,2,3,4]
y = [5,6,7,8]
z = np.add(x,y)
print(z)

Without the numpy ufunc
[6, 8, 10, 12]

with the numpy ufunc
[ 6  8 10 12]


# Create your own ufunc

In [2]:
import numpy as np
# To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.
# The frompyfunc() method takes the following arguments:
# function - the name of the function.
# inputs - the number of input arguments (arrays).
# outputs - the number of output arrays.

In [12]:
def myadd(x,y):
    return x + y

myadd = np.frompyfunc(myadd, 2, 1)
    
x = myadd([1,2,3,4], [5,6,7,8])
print(type(np.add))


<class 'numpy.ufunc'>


# SIMPLE ARITHMETIC

In [ ]:
# You can use arithmetic operation directly on numpy arrays. +-/*
# Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.
# All of the discussed arithmetic functions take a where parameter in which we can specify that condition.





In [19]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr1 = np.add(arr1,arr2)
newarr2 = np.subtract(arr1,arr2)
newarr3 = np.divide(arr1,arr2)
newarr4 = np.multiply(arr1,arr2)
newarr5 = np.mod(arr1,arr2)
newarr6 = np.divmod(arr1,arr2)


print(newarr1)
print(newarr2)
print(newarr3)
print(newarr4)
print(newarr5)
print(newarr6)

# others include: absolute, power, remainder

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[200 231 264 299 336 375]
[10 11 12 13 14 15]
(array([0, 0, 0, 0, 0, 0], dtype=int32), array([10, 11, 12, 13, 14, 15], dtype=int32))


# ROUNDING DECIMAL

In [37]:
# There are primarily 5 ways of decimals in numpy
# truncating, rounding, fix, floor, ceil

x = np.trunc([-2.6782, 3.999])
print(x)

x = np.round(3.556,2)
print("Round:", x)

arr = np.fix([-3.1666, 3.6667])
print(arr)
arr = np.floor([-3.1666, 3.6667])
print("Floor:", arr)
arr = np.ceil([-3.1666, 3.6667])
print("Ceil:", arr)

[-2.  3.]
Round: 3.56
[-3.  3.]
Floor: [-4.  3.]
Ceil: [-3.  4.]


# NumPy Logs